name=MT_BoardWheel
version=0.1.0
author=mattThurstan
maintainer=mattThurstan
sentence=Board single wheel setup.
paragraph=Single wheel setup library for long/short/skate boards. Used in longboardLight1 project.
category=Display
url=http://github.com/mattThurstan

